# Generated by Django 4.2 on 2024-02-29 12:41

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="users/default_user.png",
                upload_to=apps.users.models.avatar_file_path,
            ),
        ),
    ]
