export const TPYES = {
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_ONE_FROM_CART: "REMOVE_ONE_FROM_CART",
  REMOVE_ALL_FROM_CART: "REMOVE_ALL_FROM_CART",
  CONFIRM_CLEAR_CART: "CONFIRM_CLEAR_CART",
  CLEAR_CART: "CLEAR_CART",
};
