# Generated by Django 4.2 on 2024-02-21 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_product_category_alter_product_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="discount_value",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
