# Generated by Django 4.2 on 2024-03-06 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_product_discount_percentage_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="title",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
